### PR TITLE
Bump yuidocjs version to v0.10.0

### PR DESCRIPTION
**Pull request by okuryu**
See: https://github.com/yui/yuidoc/releases/tag/v0.10.0

### CODE REVIEW

**Comment by cibernox** [comment]
@okuryu Thanks for all your contributions. I've granted you privileges on the repo. 

You can merge it yourself now

**Comment by okuryu** [comment]
@cibernox Thanks! Could you publish to npm?

**Comment by cibernox** [comment]
published as 0.8.3

**Comment by okuryu** [comment]
:+1:

**Pull request merged**
