### PR TITLE
Bump yuidocjs version to 0.5.0

### PR DESCRIPTION
**Pull request by okuryu**
Hi, we just released v0.5.0 recently. Could you take a look?

### CODE REVIEW

**Comment by cibernox** [comment]
Cool. I haven't seen any breaking change in yuidoc's changelog, so :+1: 

ES6 rest arguments are cool. I'll bump the version after this merge and release.

**Comment by cibernox** [comment]
Many thanks!

**Comment by okuryu** [comment]
Thanks quick taking! :smiley:

**Comment by cibernox** [comment]
0.4.0 released -> https://www.npmjs.com/package/ember-cli-yuidoc

**Comment by okuryu** [comment]
Awesome! Please let me know if there're any problems. :+1:

**Pull request merged**
