### PR TITLE
Caching writer update

### LINKED ISSUE #27: Using old version of broccoli-caching-writer
https://github.com/cibernox/ember-cli-yuidoc/blob/master/package.json#L21

### PR DESCRIPTION
**Pull request by dschmidt**
Hey,

this fixes #27.

I hope you are fine with me sneaking in the `path.resolve` change, which makes the code less platform dependent and also handle absolute paths correctly. If you want a separate PR for that, I can make that happen too.

BR,
Domme

### CODE REVIEW

**Comment by cibernox** [comment]
Absolutely. 

I'm not really very up to date with all the changes that have happened in the broccoli/ember-cli ecosystem lately.

**Comment by cibernox** [comment]
I'll cut a new patch release now.

**Comment by cibernox** [comment]
Published 0.8.1

**Comment by dschmidt** [comment]
That was quick! Yay!

**Pull request merged**
